

version: '3.7'

services:
  tchat-local-dev:
    image: josephsylvan/rc:build-3.16.2-meteor-2.1.1
    restart: on-failure
    command: >
      bash -c "
        set -ex &&
        /app/prepare.sh &&
        git config --global --add safe.directory /app/Rocket.Chat &&
        cd /app/Rocket.Chat &&
        meteor npm set strict-ssl false &&
        meteor npm install --prefer-offline &&
        meteor npm install &&
        npm run dev
      "
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ..:/app/Rocket.Chat
      - ./prepare.sh:/app/prepare.sh
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      MONGO_URL: "mongodb://mongodb:27017/meteor?replicaSet=rs0"
      MONGO_OPLOG_URL: "mongodb://mongodb:27017/local?replicaSet=rs0"
      # Accounts_OAuth_Custom_A4_url: https://keycloak.com/auth
    
networks:
  default:
    name: tchat-dev-network
